$font = JetBrainsMono Nerd Font
$accent = rgba(137, 224, 224, 0.95)
$accent2 = rgba(158, 232, 160, 0.95)
$muted = rgba(154, 160, 170, 0.95)
$bg = rgba(14, 15, 20, 0.75)

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

general {
    hide_cursor = false
}

background {
    monitor =
    path = /home/kr-dev/.config/wp.png
    color = rgba(14, 15, 20, 1.0)
    blur_passes = 2
    blur_size = 7
    noise = 0.02
}

input-field {
    monitor =
    size = 16%, 4.2%
    outline_thickness = 2
    inner_color = rgba(14, 15, 20, 0.55)
    outer_color = $accent $accent2 45deg
    check_color = $accent2 $accent 120deg
    fail_color = rgba(245, 160, 160, 0.95)
    font_color = rgb(100, 100, 100)
    fade_on_empty = false
    rounding = 9999
    dots_size = 0.40
    dots_spacing = 0.28
    font_family = $font
    placeholder_text = password
    fail_text = $PAMFAIL
    position = 0, -110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%H:%M"
    font_size = 72
    font_family = $font
    color = rgb(255, 255, 255)
    position = 0, 110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 20
    font_family = $font
    color = $muted
    position = 0, 40
    halign = center
    valign = center
}

