format = """
[](fg:#3d444d bg:#161b22)\
$os$battery$username$hostname$shell\
[](fg:#3d444d bg:#161b22)\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nim\
$rust\
[](bg:#161b22 fg:#21262d)\
$character\
[ ](fg:#21262d)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[os]
style = "bg:#3d444d fg:#f0f6fc bold"
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[shell]
style = "bg:#3d444d fg:#f0f6fc bold"
format = "[$indicator]($style)"
disabled = false
fish_indicator = ' 󰈺'
powershell_indicator = ' '
bash_indicator = ''
zsh_indicator = ''

[battery]
format=  '[ $symbol$percentage]($style)'

[[battery.display]]
threshold = 25
style = 'bg:#3d444d fg:#0d1117'

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#3d444d fg:#f0f6fc bold"
style_root = "bg:#3d444d fg:#f0f6fc bold"
format = '[ $user]($style)'

[hostname]
style = "bg:#3d444d fg:#f0f6fc bold"
format = '[@$hostname ]($style)'
ssh_only = false
disabled = false

[directory]
style = "bg:#161b22 bold"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = ""


[c]
symbol = " "
style = "bg:#161b22 fg:#f0f6fc bold"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#58a6ff fg:#f0f6fc bold"
format = '[ $symbol $context ]($style) $path'

[kubernetes]
symbol = "☸ "
style = "bg:#58a6ff fg:#f0f6fc bold"
format = '[ $symbol $context ]($style)'
disabled = true

[elixir]
symbol = " "
style = "bg:#161b22"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#161b22"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#0d1117 fg:#f0f6fc bold"
format = '[](fg:#0d1117 bg:#161b22)[$symbol $branch]($style)'

[git_status]
style = "bg:#0d1117 fg:#f0f6fc bold"
format = '[ $all_status$ahead_behind]($style)[](fg:#0d1117 bg:#161b22)'

[golang]
symbol = " "
style = "bg:#161b22 fg:#f0f6fc bold"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#161b22"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#161b22 fg:#f0f6fc bold"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#161b22 fg:#f0f6fc bold"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#161b22 fg:#f0f6fc bold"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#161b22 fg:#f0f6fc bold"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#161b22 fg:#f0f6fc bold"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#f0f6fc fg:#21262d bold"
# format = '[ ♥ $time ]($style)'
format = '[$time ]($style)'

[character]
disabled = false
success_symbol = "[✓](bg:#21262d fg:#58a6ff)"
error_symbol = "[×](bg:#21262d fg:#f0883e)"
# format = '[ ♥ $time ]($style)'
format = "$symbol"